name: Tag

on:
  push:
    paths:
      - '.changeset/**'
      - 'package/**'
    branches:
      - master

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build:packages

      - name: Create release Pull request or Tag
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn tag
          commit: 'chore(tag): version packages'
          title: 'chore(tag): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
